### ISSUE TITLE
想请教个问题

### ISSUE THREAD

**Issue by z589533** [xilibi2003/learnblockchain#6]
![image](https://user-images.githubusercontent.com/12063612/38686304-9a6975a8-3ea6-11e8-9373-1d1920f18776.png)
右下角的创建好的合约，如果我刷新这个页面对这个代币合约就没办法操作了，怎么保存右下角这些方法呢

**Comment by z589533** [comment]
一刷新，就找不回这些方法，只能电脑不关机

**Comment by luoxiaohui** [comment]
你的区块是保存在内存里的，刷新后内存清零，就得重来了。

**Comment by xilibi2003** [comment]
如果合约部署在模拟环境的vm里，是这样， 可以部署到以太坊网络， 记录下 地址，下次可以load 回来
